### PR TITLE
Formatting and address some markdown linting errors

### PR DESCRIPTION
**Pull request by aknot242**

### CODE REVIEW

**Comment by 4141done** [comment]
@aknot242 Thanks for the contribution.  Is this one ready to go?

**Comment by aknot242** [comment]
Yup!

**Review by 4141done — APPROVED** [review]
Thanks again for your contribution.  Out of curiosity - what markdown linter are you using so I can incorporate markdown checks into my process?

**Comment by aknot242** [comment]
@4141done I use a VSCode extension: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Pull request merged**
